### ISSUE TITLE
Ability for Graphback to know individual field and table name customisations

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#556] opened 2019-12-12 13:01 UTC
Once https://github.com/aerogear/graphback/issues/554 is implemented, Graphback and graphql-migrations will have a common understanding of default name transformations.

```gql
type Foo {
  id: ID
  """
  @db.name: 'fooName'
  """
  name: String
```

The above example would not work with the default transformations as we have now customised a column name but Graphback is not aware of this.

**Comment by wtrocki** [comment] 2019-12-23 17:05
I think we can do 2 things:

- Add a way to cripple db migrations package to not allow for field name 
From my side this is -1000!

- Simply not allow/document field name changes for graphback - while db migration will allow it. 
This is simple and clean change that can be done in documentation
WDYT?

**Comment by wtrocki** [comment] 2019-12-23 17:23
Closed as this was duplicate of the general refactor for core mapping. This is just one of the problems that the issue will resolve. There is huge refactor needed to get this over the line

**Closed** 2019-12-23 17:22 UTC
