### ISSUE TITLE
ManyToMany Relationship

### ISSUE THREAD

**Issue by b1zzu** [aerogear/graphback#328] opened 2019-09-09 19:44 UTC
Having a ManyToMany relationship could spare some boiler template work and also make the database more performant.

For example, I have this schema:
```graphql
type User {
  id: ID!
  name: String!
  activities: [Activity]! @ManyToMany(field: "partecipants")
}

type Activity {
  id: ID!
  name: String!
  description: String
}
```
where a User can participate to has many Activities and an Activity can have many participants (Users).

This will be the expected graphql schema:
```graphql
type User {
  id: ID!
  name: String!
  activities: [Activity]!
}

type Activity {
  id: ID!
  name: String!
  description: String
  partecipants: [User]!
}
```

From the queries point of view, we can implement an optimized resolver for activities and participants, but they should be straight forward.

Instant for the mutations I have a couple of ideas:

1. An add/remove participant or activity
```graphql
type Mutation {
  addPartecipantToActivity(activityId: ID!, userId: ID!): Activity!
  removePartecipantFromActivity(activityId: ID!, userId: ID!) Activity!
  addActivityToUser(userId: ID!, activityId: ID!): User!
  removeActivityFromUser(userId: ID!, activityId: ID!): User!
}
```

2. Bulk update participants or activities
```graphql
input ActivityInput {
  # other fields
  partecipants: [ID]!
}

input UserInput {
  # ...
  activities: [ID]!
}

# and the standard update and crate mutations
```
And finally in the database should be created a table called `activieties_to_partecipants` with the `userId` and `activityId` foreign keys, and usually, the id would be the combination of the two foreign keys, but it's not always like that.

It's also important to keep in mind that it could be useful to personalize the DB table name, the foreign keys names, and the mutations names (if using the first option)

**Comment by wtrocki** [comment] 2019-09-09 19:48
Thank you so much @b1zzu.
I think we had experimented with this.

Ideally we need to have coverage for two cases:
- ManyToMany with explicit GraphQL type that will map to the joined table but it will be ignored  for CRUD generation 
- ManyToMany out of the box defined on each node (Mapping to the same table)

**Comment by b1zzu** [comment] 2019-09-09 20:12
@wtrocki both solutions look good, but we need to ensure that performance speaking one is not worse than the other and with this a mean that we should perform one single query in order to fetch the relation.

For example, I have temporarily solved the many to many relation in this way, using an additional type as a join table
```
type User {
  id: ID!
  name: String!
  activities: [Partecipant]!
}

type Participant {
  id: ID!
}

type Activity {
  id: ID!
  name: String!
  description: String
  participants: [Participant]!
}
```
but this has the big disadvantage that if I want to query (graphql) one Activity with all the participant's name I will perform a db query for each participant user.

Apart from this, I would prefer a ManyToMany relation out of the box, but it could be also interesting to have both solutions, especially in the case a user would like to have additional fields in the on the join relation.

**Comment by wtrocki** [comment] 2019-09-22 15:32
https://github.com/prisma/prisma2/blob/master/docs/relations.md#mn good read for possible approach

**Comment by b1zzu** [comment] 2019-09-23 08:55
The ManyToMany relation in Django is one of the best I've ever seen (https://docs.djangoproject.com/en/2.2/topics/db/examples/many_to_many/#) maybe we can take some ideas from it

**Comment by craicoverflow** [comment] 2019-12-16 15:21
With the new migration engine integrated bringing ManyToMany table generation this moves one step closer.

The `@db.manyToMany` annotation creates a many-to-many table.

Next steps: queries, mutations, subscriptions.

[Requires further investigation] I think we would get away without any changes to the generated schema.

**Comment by craicoverflow** [comment] 2020-01-30 13:40
For many-to-many support at schema and resolver level, we have been considering letting users define two 1:M relationships and creating a many-to-many type in their model.

AWS Amplify does something similar:

https://github.com/aws-amplify/amplify-cli/issues/91#issuecomment-419226819
https://forums.aws.amazon.com/thread.jspa?messageID=865055

**Comment by wtrocki** [comment] 2020-01-30 14:42
Awesome!

**Comment by wtrocki** [comment] 2020-02-12 12:23
We need documentation to cover this case and some example on top of the example apps to see if that approach will work

**Comment by craicoverflow** [comment] 2020-02-13 09:04
> Awesome! Then we should hide many2many on db as it will cause confusion

Yep we should completely disable it.

**Comment by craicoverflow** [comment] 2020-03-09 09:01
This can be closed since all that is required is documentation, which will come when we document relationships.

**Comment by wtrocki** [comment] 2020-04-26 14:25
Still not documented. User reported issue. Relationship documentation is hidden in wrong chapter https://graphback.dev/docs/db/dbmigrations#foreign-keys

**Comment by craicoverflow** [comment] 2020-04-27 08:01
Relationship documentation is also in data model section:
https://graphback.dev/docs/intro/datamodel#relationships

The bug isn't an issue with the documentation, but we should specify how to create a M:M

**Comment by wtrocki** [comment] 2020-04-27 08:13
Data model on is shorter - we are missing:
- info about bidirectional relationships generated 
- info about ManyToOne ( available as option)
- info about ManyToMany ( With helper table )

**Comment by craicoverflow** [comment] 2020-04-27 08:21
Adding ManyToMany now.

1. Information about generating bidirectional fields is there in DataModel:

```
This creates a one-to-many relationship between Note.comments and Comment.note. If Comment.note does not exist Graphback will generate it for you, otherwise you can define it yourself.
```

2. We haven't documented ManyToOne because manually specifying ManyToOne will not generate the metadata or OneToMany field.
We decided not to implement this because it is less confusing and easier to add the OneToMany side.

3. Adding ManyToMany info now.

**Comment by wtrocki** [comment] 2020-04-27 08:40
> We haven't documented ManyToOne because manually specifying ManyToOne will not generate the metadata or OneToMany field.

Oh.. I did not know about it. Good to add this to docs as well.

**Comment by wtrocki** [comment] 2020-05-06 09:19
Docs landed but I still think we need to have better support for this kind of relationship

**Comment by machi1990** [comment] 2020-05-06 10:18
> Docs landed but I still think we need to have better support for this kind of relationship

Agreed. I am trying out the suggested solutions in the doc in OVP, will try to gather some ideas.

**Comment by craicoverflow** [comment] 2020-09-14 14:37
Closing as duplicate of #2023

**Closed by craicoverflow** 2020-09-14 14:37 UTC
Labels: CRUD, services-crud
