### ISSUE TITLE
Error when generating backend using graphql-cli

### ISSUE THREAD

**Issue by Artimunor** [aerogear/graphback#1183] opened 2020-04-26 13:48 UTC
when using graphql-cli, after initalizing a project and defining a datamodel (.graphql schema with annotations) some errors emerge.
it's hard to tell what is the cause since i can not find good documentation beyond the basic explanation for graphback, is graphback (and that documentation) still valid? or is it part of graphql-cli now and changed?

the error:
```
...node_modules/.bin/graphql generate --backend
✖ Cannot use GraphQLObjectType "WPEntity" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

so this is after initializing a new graphql-cli project, then adjusting the datamodel.graphql (14 interrelated tables/entities)  doing a yarn install, and then running `yarn graphql generate --backend`

adding the following after dev dependencies is a workaround to not make the error appear:
```json
  "resolutions": {
    "graphql": "15.0.0"
  },
```
(same version as in the devDependencies)
run yarn install again after adding this

**Comment by wtrocki** [comment] 2020-04-26 14:35
All our templates need to have GraphQL in node package.json resolutions. 

As extension we might bring some of the CLI features to Graphback package and have lightweight GraphQL CLI that will be used on global scope only

**Comment by craicoverflow** [comment] 2020-04-28 10:52
![](https://github.trello.services/images/mini-trello-icon.png) [[Graphback] New CRUD specification](https://trello.com/c/P9nwQRgz/62-graphback-new-crud-specification)

**Comment by craicoverflow** [comment] 2020-06-08 10:07
is this fixed?

**Comment by wtrocki** [comment] 2020-06-08 10:38
This is duplicate of the GraphQL 15 migration

**Closed by wtrocki** 2020-06-08 10:38 UTC
Labels: bug
