### ISSUE TITLE
Create plugin for client side forms generation

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#808] opened 2020-03-01 06:15 UTC
We can use uniforms to generate list -> detail page etc

**Comment by wtrocki** [comment] 2020-03-09 08:08
Cc @kingsleyzissou

**Comment by kingsleyzissou** [comment] 2020-03-19 22:50
@wtrocki, we can maybe have a chat about this tomorrow. but documenting it here too. I started hashing things out, but I've hit a block.

Uniforms uses a bridge between the schema and the auto-generated forms, so we have a couple of options there:

1. Expose the schema to the client and let the client build the bridge for the forms. However, since the schema is being generated from the backend, this seems a bit wasteful.

2. Use the generated schema and build the bridge on the server-side. The issue with this would be how we could expose the bridge to the client.

3. Try build our own thing without Uniforms, but that seems like a lot of work.

**Comment by wtrocki** [comment] 2020-03-19 23:17
Uniforms works with GraphQL schema but it will also work with input types. Exposing specific input types to client is inevitable. Most of the competitors putting entire schema introspection to the client and use it to generate code. 

In our case we might to actually generate more rich JSON schema format etc. Using JSON schema will be not only much better in terms of performance and scalability but also we can use existing db annotations like length of the string.
Doing this will also enable different frameworks like angular- there are tons of the forms generators for JSON schema for every framework. 

Ad 1. We ideally need to expose chunks of schema for models that have specific annotation. Master detail view with create delete and edits. Compiling schema on client is heavy. Most of the prod apps will have server schema on client for coverage and validation.

Ad 2. Uniforms work best with compiled schema we can represent schema as GraphQL objects aka introspection. Every server already does it in non production mode

Ad 3. How about master detail page. Do we have libraries for this? It seems like there are some universal libs that do listviews etc. If we pick right format like JSON schema we can represent and validate data

**Comment by wtrocki** [comment] 2020-03-19 23:35
Looking for feedback @troZee @ardatan 
Do you like to have generated List -> Detail -> Edit views for React/RN or there is no value in this and simple JSON schema with formik will work

FYI @cristianonicolai - if graphback generate UI from GraphQL schemas would Kogito would benefit from it?

**Comment by cristianonicolai** [comment] 2020-03-20 13:08
@wtrocki possibly yes, although we were looking into creating a JSON schema out of POJOs. JSON schema seems to be supported by quite a few client frameworks, that would be our first try at this stage.

**Comment by wtrocki** [comment] 2020-03-20 13:21
Ok. This confirms that JSON schema is the way to go then.

**Comment by troZee** [comment] 2020-03-20 21:40
Generating forms based on schema would be hard, because it has lot of constraints. The library must be flexible for dev. Some of them can use different UI libraries/styles and it would be hard, to create some kind of adapter for all of them. There are also differences between frameworks like react and react native (business logic would be the same, but different JSX). 

From my perspective it is better to implement forms on my own, because I can easily customize all requirements, which has been provided by business.   

Also what in case, when someone use different solution than uniforms ? like formik, own implementation, own form lib ?

**Comment by wtrocki** [comment] 2020-03-21 20:38
I have been chatting with couple devs and got some feedback:
1) master detail as framework do not make sense. It could be just as some reference implementation or template. With that in mind we already have master detail in datasync-starter that needs work
2) Generation of forms that is generic is deemed to fail or not provide much value. There are so many frameworks, style libraries or even approaches for web. Ideally people will simply build some sample app with some tech and blog post about it. For example topic could be something like "Writing your Gatsby website with Graphback, Keycloak and Offix"

This will provide much more value to users and also will help people to find some solutions for their needs.

**Comment by wtrocki** [comment] 2020-03-24 12:29
Update: We have decided to give it a go and come up with auto-generation of forms using Uniforms. This will involve the creation of the AutoForm that will support:

- Ionic
- Patternfly 

CC @radekmie

**Comment by radekmie** [comment] 2020-03-24 17:56
A bit late, but here are my two cents:
* GraphQL schema is _enough_ to render a form that will pass the GraphQL validation. The thing is that in most cases we do use an additional layer of validation to express business logic. Some simple ones like min/max string length, matching a regex or min/max value can be easily encoded within the GraphQL schema (using directives). The problem is that there's a lot of other rules (like _x + y > z_ or _x xor y_) that are common and very non-local (include multiple values or have no clear source of the problem). In that case, using JSON schema is great, as it's still very simple (and serializable!) yet so expressive.
* uniforms (not Uniforms!) is a very flexible library, and a field doesn't have to be _field per se_ - any component will do. This allows designing any kind of crazy designs in the schema, without touching JSX at all. It may not be the best choice because the schema may get big, but this possibility means that you can combine any kind of meta information you have (GraphQL schema, GraphQL directives, other annotations, configuration objects or even custom code) into a valid schema with its layout.
* You can think about uniforms in a plug'n'play way, as every `AutoForm` will use its `children` if defined - automatically generated content is just a fallback (in a way). The main goal here is to wire the logic (schema, validation) and keep the UI separated (JSX, schema or both).

If you'll have any questions or problems with uniforms, feel free to ping me (just like you did), use our [Gitter](https://gitter.im/vazco/uniforms) or create an issue.

**Comment by kingsleyzissou** [comment] 2020-04-20 09:55
Closing this issue.

We won't be building a package/plugin to generate JSON schema to be used with a uniforms bridge, since this is easy to implement already.

I have built two uniforms packages for our needs, one for patternfly and one for ionic.

They can be found here:
- https://github.com/kingsleyzissou/uniforms-patternfly
- https://github.com/kingsleyzissou/uniforms-ionic

**Closed by kingsleyzissou** 2020-04-20 09:55 UTC
