### ISSUE TITLE
graphback not found 0.14.0-alpha1

### ISSUE THREAD

**Issue by lastmjs** [aerogear/graphback#1341] opened 2020-05-29 16:31 UTC
If I only install `graphback`, the `graphback` executable in node_modules/.bin is not found. Shouldn't it be there when installing `graphback`? I have to install `graphback-cli` to get the `graphback` command to work.

**Comment by wtrocki** [comment] 2020-05-31 14:48
graphback is library. Grapback-cli is command line tool. 
The library doesn't require graphql and cli does (without that we will have ugly graphql.js conflicts).

We will need to see if we can pull out all commands to graphback etc. to make this simpler.

**Comment by craicoverflow** [comment] 2020-06-09 11:26
Closing as duplicate of https://github.com/aerogear/graphback/issues/1328

**Closed by craicoverflow** 2020-06-09 11:26 UTC
