### ISSUE TITLE
Redefine format for the Graphback ID definitions

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#1272] opened 2020-05-14 13:41 UTC
Graphback allows developers to set up ID as different values. 
We need to think how to properly document ID definition and tests how custom ID's will work with our CRUD spec etc.

Custom ID's should be also indexed by default (this applies to Mongo)

**Comment by craicoverflow** [comment] 2020-05-14 13:50
To add to this - there is a discrepancy between Graphback runtime and graphql-migrations. GraphQL Migrations requires an `id: ID` field - is this what we want? it seems to contradict Graphback's support of custom ID fields.

For `findOne`, there should not be an issue with defining a `<Model>UniqueInput` input type - in fact this makes it easier for developers who may have a unique constraint on a combination of fields.

**Comment by ssd71** [comment] 2020-05-14 15:06
Where should we setup indexing for mongo? I wonder if we can use the schema object to get info about custom ID? If so, maybe we could add custom field indexing as well as foreign key field indexing in tandem with these features

**Comment by wtrocki** [comment] 2020-05-14 15:45
I think prototype could be doing indexing when DataProvider is constructed using ensureIndex. Once we confirm that this approach is reasonable we can think about how to hook that properly.

**Comment by machi1990** [comment] 2020-07-27 17:25
@wtrocki is this a duplicate of https://github.com/aerogear/graphback/issues/1547?

**Comment by wtrocki** [comment] 2020-07-27 17:32
Looks like it for me

**Comment by machi1990** [comment] 2020-07-27 18:00
Closing in favour of #1547

**Closed** 2020-07-27 18:00 UTC
Labels: mongodb
