### ISSUE TITLE
No result from database...can't override resolvers in resolvers object

### ISSUE THREAD

**Issue by lastmjs** [aerogear/graphback#1843] opened 2020-08-09 04:04 UTC
I need the ability to override resolvers of model objects. I believe I was able to do this in previous versions of graphback during the alpha, and I did this with Prisma. It isn't working anymore. For example:

```graphql
"""@model"""
type Companies {
  id: ID!
  test: Int!
}
```
`test` is not in the database, I am going to write a resolver for it. In the past I would overwrite that field in my resolvers object:

```typescript
    const { 
        typeDefs,
        resolvers,
        contextCreator
    } = buildGraphbackAPI(model, {
        dataProviderCreator: createKnexDbProvider(knexDB)
    });

  const newResolvers = {
     ...resolvers,
     Companies: {
       ...resolvers.Companies,
       test: () => 5
     }
  };
```
I would then take `newResolvers` and give it to Apollo Server. This doesn't work for some reason, and I keep getting the following error: `"No result from database: Cannot find a result for companies with filter: {\"id\":\"1\"}"`

**Comment by machi1990** [comment] 2020-08-09 04:04
Automatically generated comment to notify maintainers
/cc @craicoverflow, @machi1990, @wtrocki

**Comment by lastmjs** [comment] 2020-08-09 04:10
Related to this: https://github.com/aerogear/graphback/issues/1432

**Comment by wtrocki** [comment] 2020-08-09 08:57
The error we see is not related to resolver it is more than a database cannot be queried with provided id. 

https://github.com/aerogear/graphback/blob/f8ab9f3cf4a8fe58379a0eac1655f0e9c825d82b/packages/graphback-runtime-knex/src/KnexDBDataProvider.ts#L72

**Comment by machi1990** [comment] 2020-08-10 06:57
Looking at your snippet I do not see anything alarming so indeed, this is what @wtrocki says it is. Let us know how if this works when changing the requested `id` to something else.

**Comment by lastmjs** [comment] 2020-08-10 17:03
The company that I am querying indeed exists in the database. For example, this query works:

```graphql
query {
  getCompanies(id: 1) {
    id
  }
}
```
and returns the following:

```json
{
  "data": {
    "getCompanies": {
      "id": "1"
    }
  }
}
```
But when I add the test field that has a custom resolver hooked up like I showed in previous comments:

```graphql
query {
  getCompanies(id: 1) {
    id
    test
  }
}
```
This does not work, and I get the following result:

```json
{
  "errors": [
    {
      "message": "No result from database: Cannot find a result for companies with filter: {\"id\":\"1\"}",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "getCompanies"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: No result from database: Cannot find a result for companies with filter: {\"id\":\"1\"}",
            "    at KnexDBDataProvider.<anonymous> (/home/lastmjs/development/jill/jills-office-node/node_modules/@graphback/runtime-knex/src/KnexDBDataProvider.ts:75:13)",
            "    at Generator.throw (<anonymous>)",
            "    at rejected (/home/lastmjs/development/jill/jills-office-node/node_modules/tslib/tslib.js:113:69)",
            "    at processTicksAndRejections (internal/process/task_queues.js:85:5)"
          ]
        }
      }
    }
  ],
  "data": {
    "getCompanies": null
  }
}
```

**Comment by machi1990** [comment] 2020-08-10 17:58
Thanks for checking @lastmjs, I fully understand now, previous I was thinking that the field `test` is in the database also. But now I understand. It might be a bug since from the ResolversInfo we'll issue a query like 
```
select id, test from companies where id = xxx
```

Which fails with a missing column error. 

I am thinking maybe we can introduce a way to ignore some fields from database selection?  I know we have [`@db(skip: true)`](https://graphback.dev/docs/0.14.x/graphql-migrations/db-design#ignore-a-field) that's ignores a field only when running migrations. 
 
/cc @craicoverflow @wtrocki

**Comment by lastmjs** [comment] 2020-08-10 18:03
The issue seems to run even deeper, and based on my limited knowledge of Graphback's internals, I would say this has to do with how the dataloader attempts to resolve relations (probably similar to what you're saying @machi1990). I have a custom query that looks like this: 

```graphql
Query {
  fetchLiveQueue: [Incoming_queue_items!]!
}

""" @model """
type Incoming_queue_items {
    id: ID!

    """
    @oneToOne(key: 'call_id')
    """
    call: Calls!
    created_at: DateTime!
    handled_at: DateTime
    incoming_call_type: INCOMING_CALL_TYPE!

    """
    @oneToOne(key: 'pod_id')
    """
    pod: Pods!
    updated_at: DateTime!
    user_call_sid: String!
}
```
When I execute the following query:

```graphql
query {
  fetchLiveQueue {
    pod {
      id
    }
  }
}
```
I get the following error:

```graphql
{
  "errors": [
    {
      "message": "No result from database: Cannot find a result for pods with filter: {}",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "fetchLiveQueue",
        0,
        "pod"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: No result from database: Cannot find a result for pods with filter: {}",
            "    at KnexDBDataProvider.<anonymous> (/var/task/node_modules/@graphback/runtime-knex/dist/KnexDBDataProvider.js:73:23)",
            "    at Generator.throw (<anonymous>)",
            "    at rejected (/var/task/node_modules/tslib/tslib.js:113:69)",
            "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
          ]
        }
      }
    }
  ],
  "data": null
}
```
`fetchLiveQueue` has a completely custom resolver, and thus should be completely outside of the scope of Graphback's resolvers and dataloader pattern. This is a bit of a big issue for me right now

**Comment by machi1990** [comment] 2020-08-10 18:46
Thank you @lastmjs for digging deeper. 

Glad that you have found a workaround for now, do you mind posting a code snippet here in the issuse so that it could be useful for others users while the team is further triaging this issue? Thank you.

**Comment by lastmjs** [comment] 2020-08-10 21:52
Sure, the workaround is simple. Just make a custom type without a @model annotation.

```graphql
Query {
  fetchLiveQueue: [FetchLiveQueueIncomingQueueItems!]!
}

# Simplified example, but just add the fields that you need
type FetchLiveQueueIncomingQueueItems {
  id: ID!
  created_at: DateTime!
  pod: FetchLiveQueueIncomingQueuePods!
}

type FetchLiveQueueIncomingQueuePods {
  id: ID!
}

""" @model """
type Incoming_queue_items {
    id: ID!

    """
    @oneToOne(key: 'call_id')
    """
    call: Calls!
    created_at: DateTime!
    handled_at: DateTime
    incoming_call_type: INCOMING_CALL_TYPE!

    """
    @oneToOne(key: 'pod_id')
    """
    pod: Pods!
    updated_at: DateTime!
    user_call_sid: String!
}
```

**Comment by craicoverflow** [comment] 2020-08-11 08:18
> I am thinking maybe we can introduce a way to ignore some fields from database selection?  I know we have [`@db(skip: true)`](https://graphback.dev/docs/0.14.x/graphql-migrations/db-design#ignore-a-field) that's ignores a field only when running migrations. 

@machi1990 yes that would make sense. I touched on this in https://github.com/aerogear/graphback/issues/1023 - if there was an `@ignore` annotation this could be used for both cases - ignore a field not in the database and ignore a field in the database table.

**Comment by machi1990** [comment] 2020-08-11 08:35
@craicoverflow cool, `@ignore` makes sense. Let me add a comment in that issue.

**Comment by lastmjs** [comment] 2020-08-11 23:20
I'm not sure `@ignore` would solve the problem I'm having, unless you put `@ignore` on the custom query `fetchLiveQueue`. In my example above, `Incoming_queue_items` is in the database, and the Graphback-generated queries should use the database and do batching and dataloader things. But, for my custom queries I am just using `Incoming_queue_items` as a type, and fetching the data myself.

**Comment by machi1990** [comment] 2020-08-12 07:26
@lastmjs the `@ignore` annotation will be placed directly on the fields that should not be loaded from the database. 

Taking this exap

> 
> ```graphql
> """@model"""
> type Companies {
>   id: ID!
>   test: Int!
> }
> ```
> 
> `test` is not in the database, I am going to write a resolver for it. In the past I would overwrite that field in my resolvers object:

For example, you could use it in the model above as: 

 ```graphql
 """@model"""
type Companies {
   id: ID!
  """
 @ignore
  """ 
  test: Int!
 }
```

and it will:
 - ignore the `test` field from the query issued in database, thus avoid a `missing column error` which resulted in the issue you were seeing.
- not generate the mutation inputs, since the `test` field is not in the database. This will avoid similar errors during create/update/delete
- the `test` field will be omitted from the generate `CompaniesFilterInput`, again for the same reason.
- moreever, if you are using GraphQLMigrations, this field will be skipped and not generated.

All these points above are due to the fact that `test` is a transient field and Graphback should not attempt to manage it in either way. 


Going to this https://github.com/aerogear/graphback/issues/1843#issuecomment-671503126, maybe the `@ignore` field will not be appropriate ( I am yet to find out why you are having this issue). Do you mind sharing in a sample code the query you are issue in the database? There are two possibilities:
- 1. There is actually no data for this particular case
- 2. There is an issue that's slightly different and not related to the one that I finally grasped (a missing column in the database). 

Having a small code snippet in how the query is issued will be helpfully in understanding this second issue. Thank you.

**Comment by lastmjs** [comment] 2020-08-14 19:12
Hey, is the example here good enough? https://github.com/aerogear/graphback/issues/1843#issuecomment-671503126

This is the query:

```graphql
query {
  fetchLiveQueue {
    pod {
      id
    }
  }
}
```
The example schema is in that comment

**Comment by machi1990** [comment] 2020-08-17 13:12
Thank you @lastmjs I'll try to setup something similar in an attempt to reproduce the issue.

**Comment by machi1990** [comment] 2020-09-09 13:14
@lastmjs ping, I was thinking about this issue again and was wondering if you take a look at https://github.com/aerogear/graphback/issues/1843#issuecomment-678524738 and https://github.com/aerogear/graphback/issues/1843#issuecomment-678554357, thanks :-)

**Comment by craicoverflow** [comment] 2020-09-14 14:34
Closing as this looks to be resolved, but reopen if I am wrong on that.

**Closed by craicoverflow** 2020-09-14 14:34 UTC
Labels: bug
