### ISSUE TITLE
Validation for relationships fails on valid case

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#2019] opened 2020-09-09 08:56 UTC
Problem with OpenVolunteerModel

```
Error: Volunteer.actions and VolunteerAction.volunteer 'key' annotations are different. Ensure both are the same or remove one so that it can be generated.
```

https://github.com/aerogear/OpenVolunteerPlatform/blob/master/platform/server/model/main.graphql#L38-L41

The action doesn't have a key specified and ManyToOne side has (this was just copied from the generated schema for visibility of the field in the schema)

Error is confusing as key is not there. Removing key from manyToOne will fix it.

**Comment by machi1990** [comment] 2020-09-09 08:57
/cc @craicoverflow, @machi1990
Automatically generated comment to notify maintainers

**Comment by wtrocki** [comment] 2020-09-09 09:29
I'm not sure if there is some fix here.

**Comment by wtrocki** [comment] 2020-09-09 10:53
This is a bug. Little bit debugging showed me that result schema has some extra annotations generated and ends up with 2 annotations under single object:

<img width="807" alt="Screenshot 2020-09-09 at 11 52 59" src="https://user-images.githubusercontent.com/981838/92589824-0ec30e80-f293-11ea-89f1-bcb4676f0fd4.png">

**Comment by wtrocki** [comment] 2020-09-09 10:57
So trick that I have done is:

- Generate schema
- When to schema to take generated fields and include them into model (they should be ok to be in the model.
- Generate code:

```
<b>Generation failed: Error: Volunteer.actions and VolunteerAction.volunteer 'key' annotations are different. Ensure both are the same, or remove one so that it can be generated.</b>
```

**Comment by wtrocki** [comment] 2020-09-09 10:57
See also #2020

**Comment by craicoverflow** [comment] 2020-09-09 11:21
What happens when you remove all manyToOne annotations from the data model? It should succeed

**Comment by wtrocki** [comment] 2020-09-09 11:23
It will fail validation (unless this change is applied)

**Comment by craicoverflow** [comment] 2020-09-09 11:24
Can you show me the output?

**Comment by craicoverflow** [comment] 2020-09-09 11:33
Can you reproduce this error using the models from the templates? They are smaller and more focused so it is easier to see why the error occurs - as in OVP the model is large and there could be other schema errors.

**Comment by machi1990** [comment] 2020-09-09 11:59
> So trick that I have done is:
> 
> * Generate schema
> * When to schema to take generated fields and include them into model (they should be ok to be in the model.
> * Generate code:
> 
> ```
> <b>Generation failed: Error: Volunteer.actions and VolunteerAction.volunteer 'key' annotations are different. Ensure both are the same, or remove one so that it can be generated.</b>
> ```

I think this https://github.com/aerogear/graphback/blob/52014578abf4f8cd072ba971cbf116485da5b517/packages/graphback-core/src/relationships/RelationshipMetadataBuilder.ts#L292 

will need changing so that it compares the two keys if they are both defined (*read as user defined values*) since if they are not defined they'll be generated with key info:
- https://github.com/aerogear/graphback/blob/52014578abf4f8cd072ba971cbf116485da5b517/packages/graphback-core/src/relationships/RelationshipMetadataBuilder.ts#L226
- https://github.com/aerogear/graphback/blob/52014578abf4f8cd072ba971cbf116485da5b517/packages/graphback-core/src/relationships/RelationshipMetadataBuilder.ts#L248
- https://github.com/aerogear/graphback/blob/52014578abf4f8cd072ba971cbf116485da5b517/packages/graphback-core/src/relationships/RelationshipMetadataBuilder.ts#L205 

What's your thoughts on this @craicoverflow ?

**Comment by craicoverflow** [comment] 2020-09-09 13:00
> will need changing so that it compares the two keys if they are both defined (read as user defined values)

That sounds better - this way you could have a manyToOne annotation with the key property and it would get updated, am I right?

I think these patches we make to `RelationshipBuilder` will not make the class any easier to work with, and I wonder whether #2023 should be focused on, as this particular issue raised I don't think is the root of the problem.

**Comment by machi1990** [comment] 2020-09-09 13:03
> > will need changing so that it compares the two keys if they are both defined (read as user defined values)
> 
> That sounds better - this way you could have a manyToOne annotation with the key property and it would get updated, am I right?
> 
> I think these patches we make to `RelationshipBuilder` will not make the class any easier to work with, and I wonder whether #2023 should be focused on, as this particular issue raised I don't think is the root of the problem.

+1 on this.

**Comment by craicoverflow** [comment] 2020-09-14 14:36
Closing as the case was valid and working as intended (it actually caught an invalid relationship association in the model). There is an issue #2023 to track a general improvement of relationships.

**Closed by craicoverflow** 2020-09-14 14:36 UTC
Labels: bug, triage
