### ISSUE TITLE
Disable db and generation for smaller types

### ISSUE THREAD

**Issue by ankitjena** [aerogear/graphback#198] opened 2019-08-06 16:17 UTC
## Background
Currently the `Tasks` schema is 
```
type Task {
  id: ID!
  version: Int
  title: String!
  description: String!
  status: String!
  creationMetadata: CreationMetadata
  assignedTo: User
}

type CreationMetadata {
   createdDate: String
   createdBy: User
 }

type User {
  id: ID!
  firstName: String!
  lastName: String!
  title: String!
  email: String!
}x`

## Custom queries and mutations
type Query {
  allCompletedTasks(first: Int, after: String): [Task],
}

type Mutation {
  checkAndUpdateTask(id: ID!, title: String, description: String, version: Int!, status: String!): Task
}

```
On running `generate` and `db` it generates resolvers with CRUD operation and creates db resources even for the `CreationMetadata` type, which we don't want. We should disable these smaller types.

```
findCreationMetadatas: (_: any, args: any, context: GraphQLContext) => {
      return context.db.select().from('creationmetadata').where(args.fields)
}
.....
.....
findCreationMetadatas(fields: CreationMetadataFilter!): [CreationMetadata!]!
```

**Comment by ankitjena** [comment] 2019-08-06 16:21
@wtrocki The `@disablegen` method mentioned in issue #187 can be used for this I think

**Comment by wtrocki** [comment] 2019-08-06 16:23
yeah. This is better duplicate of #187 we can close other one and keep one there.

**Comment by richcorbs** [comment] 2019-08-10 19:41
PR submitted for this one:

https://github.com/aerogear/graphback/pull/215

**Closed** 2019-08-10 22:03 UTC
Labels: bug, core
