### ISSUE TITLE
Relationships are not synced for the datasync (Offix Datastore relies on them to get data)

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#2163] opened 2020-10-06 19:01 UTC
ObjectDelta missing relationship fields.

**Comment by machi1990** [comment] 2020-10-06 19:01
/cc @ssd71
/cc @craicoverflow, @machi1990
Automatically generated comment to notify maintainers

**Comment by wtrocki** [comment] 2020-10-06 19:01
FYI @kingsleyzissou - I need to fix that first to get over the required data in order to filter it.

**Comment by craicoverflow** [comment] 2020-10-07 08:23
This is down as a `bug` - but this was intended behaviour and a known limitation until now. Should it be a `feat`?

**Comment by wtrocki** [comment] 2020-10-07 08:35
Delta should contain exactly the state of the database. I see it as bug but not problem to make it feature :D

**Comment by craicoverflow** [comment] 2020-10-07 08:37
That's fine, let us keep it as a bug.

**Comment by craicoverflow** [comment] 2020-10-07 08:37
Docs will also need to be updated to include relationships in delta object.

**Comment by RinkiyaKeDad** [comment] 2021-01-19 09:12
Hey could I work on this issue? Can you please provide some more details about what needs to be done?

**Comment by wtrocki** [comment] 2021-01-20 12:41
I think @kingsleyzissou worked on this issue and we could technically close it due to solution available outside graphback. @kingsleyzissou Please close if you are happy with this

**Comment by kingsleyzissou** [comment] 2021-01-21 09:50
Yep, I'll close this issue

**Closed by kingsleyzissou** 2021-01-21 09:50 UTC
Labels: bug, datasync, triage
