### ISSUE TITLE
Client side query expansion is not working for generated fields

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#1167] opened 2020-04-22 16:27 UTC
When a relationship is not specified explicitly expansions will not work

**Comment by wtrocki** [comment] 2020-04-22 16:28
The workaround is to explicitly specify relationship (copy from schema)

**Comment by Eunovo** [comment] 2020-04-23 12:42
Please assign to me

**Comment by wtrocki** [comment] 2020-04-23 14:22
@Eunovo That is somehow related to the fact that model do not need to contain both sides of the relationships but schema might be. This issue is mostly related to the approach we take and it could be hard to fix without changing approach. 

You are welcomed to investigate the issue but it can be challenging to fix it.

**Comment by Eunovo** [comment] 2020-04-25 11:43
I see that expanded fields are not generated if the relationship is not specified because codegen-client doesn't build model relationships before generating queries but the relationships exist in the generated schema because the codegen-schema module builds the relationships not specified before generating the schema. Is that right?

**Comment by wtrocki** [comment] 2020-04-25 12:49
I think all depends on how relationships are build and added. The general rule is that schema plugin should be the first and it should add all related fields to the schema that later will be processed by client plugin. Somehow this is not happening - it could be that schema is not being built properly or actual transformation happens in `createResources` function

**Comment by Eunovo** [comment] 2020-04-25 13:39
Can you point to the code that enforces the "Schema plugin first" order?

**Comment by wtrocki** [comment] 2020-04-25 14:26
It is just how plugins are ordered now. This requires debugging no tell what is the problem

**Comment by Eunovo** [comment] 2020-04-25 16:41
So, I played around with a test graphback project a bit. I removed one side of the relationship declaration for the model. I messed up the plugin ordering for the project. It didn't affect the generated resolvers and client fragments; as the generated fragment still has the Expanded fields.

**Comment by Eunovo** [comment] 2020-04-25 16:42
Also, `GraphbackCoreMetadata.getModelDefinitions()` always builds relationships from input schema. I confirmed this in several tests.

**Comment by Eunovo** [comment] 2020-04-25 16:51
Modifying `graphback-codegen-client/tests/mock.graphql` to exclude one side of the relationship declaration reveals that relationships are generated in metadata as expected but query generation does not use these relationships to generate the Expanded fields. Modifying the code to use these relationships could solve the problem. I haven't seen how `SchemaCRUDPlugin` could have caused the problem. The schema is transformed in `transformSchema` and `createResources` only contains code to format schema and write to file.

**Comment by wtrocki** [comment] 2020-04-25 17:25
> GraphbackCoreMetadata.getModelDefinitions...

That is our bug. if schema from schema plugin will be used all should work

**Comment by Eunovo** [comment] 2020-04-30 13:54
@wtrocki [this a link to code on my fork that tests SchemaCRUDPlugin.transformShema](https://github.com/Eunovo/graphback/blob/df765fb4629a614a00dce57f56362a57ed8ce2d9/packages/graphback-codegen-schema/tests/GraphQLSchemaCreatorTest.ts#L74). Also, `GraphbackCoreMetadata.getModelDefinitions()` already uses current schema as shown [here](https://github.com/Eunovo/graphback/blob/df765fb4629a614a00dce57f56362a57ed8ce2d9/packages/graphback-core/src/plugin/GraphbackCoreMetadata.ts#L70)

**Comment by wtrocki** [comment] 2020-04-30 13:58
Let's create PR to see how we can action this

**Closed** 2020-05-09 07:49 UTC
Labels: bug
